/*Given two strings s and t which consist of only lowercase letters.
String t is generated by random shuffling string s and then add one more letter at a random position.
Find the letter that was added in t.*/

#include<iostream>
#include<string>

class Solution 
{
public:
	char findTheDifference(std::string s, std::string t) 
	{
		size_t found;
		for (int i = 0; i < t.length(); i++)
		{
			found = s.find(t[i]);
			if (found == std::string::npos)
			{
				return t[i];
			}
			else
				s[found] = '0';
		}
		return '0';
	}
};

int main()
{
	Solution s1;
	std::cout << s1.findTheDifference("a", "aa");
	return 0;
}
